### PR TITLE
Revert Splunk HEC logging

### PR DESCRIPTION
**Pull request by adamgraves-choices**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of mongodb-updater succeeded (http://mongodb-updater-pr-6.dev.beta.nhschoices.net)

**Review by markysoft — DISMISSED** [review]
Needs splunk fields removing from both services in docker-compose.yml

**Review by st3v3nhunt — DISMISSED** [review]
LGTM
Change has been made due to Docker daemon having problems with the Splunk log driver

**Comment by st3v3nhunt** [comment]
@adamgraves-choices Have you seen this needs some changes?

**Comment by c2s-dev** [comment]
:rocket: deployment of mongodb-updater succeeded (http://mongodb-updater-pr-6.dev.beta.nhschoices.net)

**Review by st3v3nhunt — APPROVED** [review]
LGTM

**Pull request merged**
