### PR TITLE
Splunk HEC Configuration

### PR DESCRIPTION
**Pull request by adamgraves-choices**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of mongodb-updater succeeded (http://mongodb-updater-pr-3.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of mongodb-updater succeeded (http://mongodb-updater-pr-3.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of mongodb-updater succeeded (http://mongodb-updater-pr-3.dev.beta.nhschoices.net)

**Review by st3v3nhunt — APPROVED** [review]
LGTM

**Pull request merged**
