### PR TITLE
:wrench: update connection settings to use replica sets

### PR DESCRIPTION
**Pull request by markysoft**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of mongodb-updater succeeded (http://mongodb-updater-pr-11.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of mongodb-updater succeeded (http://mongodb-updater-pr-11.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of mongodb-updater succeeded (http://mongodb-updater-pr-11.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of mongodb-updater succeeded (http://mongodb-updater-pr-11.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of mongodb-updater succeeded (http://mongodb-updater-pr-11.dev.beta.nhschoices.net)

**Comment by markysoft** [comment]
No longer required

**Pull request closed without merging**
