### PR TITLE
:two: host both db updaters in same stack

### PR DESCRIPTION
**Pull request by markysoft**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of mongodb-updater succeeded (http://mongodb-updater-pr-2.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of mongodb-updater succeeded (http://mongodb-updater-pr-2.dev.beta.nhschoices.net)

**Review by st3v3nhunt — COMMENTED** [review]
Looks good. What do you reckon to this having an ADR for the reasoning to run both in a single stack? Is it worth it, is it something we are going to want to know why it was done in 6 months time?

**Comment by markysoft** [comment]
Good point, I'll add one

**Comment by c2s-dev** [comment]
:rocket: deployment of mongodb-updater succeeded (http://mongodb-updater-pr-2.dev.beta.nhschoices.net)

**Review by st3v3nhunt — APPROVED** [review]
LGTM

**Pull request merged**
